### ISSUE TITLE
Insert or fail

### ISSUE THREAD

**Issue by Zizaco** [leroy-merlin-br/mongolid#10]
Right now, the `save` method performs an upsert in MongoDB. It would be usefull to have a method like `saveUnique` that would perform a [real insert](http://docs.mongodb.org/manual/reference/method/db.collection.insert/) in MongoDB, which will throw an exception if a document with the given _id already exists.

**Comment by rscafi** [comment]
@Zizaco is the behavior on v2 the same? we need to address it?

**Comment by mobeen122** [comment]
wouldn't the _id be different every time you add record since its generated through timestamp

**Comment by ravanscafi** [comment]
No use-case right now, closing it. Feel free to send PR's if it is still relevant.
