### ISSUE TITLE
Ioc::make Call to a member function make() on null

### ISSUE THREAD

**Issue by lpj145** [leroy-merlin-br/mongolid#107]
Bem, como não nenhuma issue falando disso, resolvi abrir um, estou testando aqui a lib de vocês, e desde já quero agradecer muito pelo trabalho e empenho de vocês, assisti seu vídeo @Zizaco falando sobre mongo e a leroy.
meu código ta aqui:
https://gist.github.com/lpj145/e3cf5d5b44e7393806e1d589c8c0a956

estou recebendo o seguinte erro: ncaught Error: Call to a member function make() on null in C:\www\mongolidtest\vendor\leroy-merlin-br\mongolid\src\Mongolid\Container\Ioc.php:42

Verificando aqui não consegui achar, alguém pode me da uma luz, de como resolver, tenho que incluir o bootstrap no meu aplicativo ?

**Comment by rscafi** [comment]
Cara, realmente, faltou colocar nas docs a parte do bootstrap.

Ao invés de usar o `vendor/autoload.php`, por favor use o `vendor/leroy-merlin-br/mongolid/bootstrap/bootstrap.php`.

Vamos pensar numa forma de ou atualizar as docs ou tirar a dependência do bootstrap.
Valeu pelo interesse :wink:

**Comment by lpj145** [comment]
se a ideia é set o container no inicio da aplicação, por que não incluímos isso num script para o próprio composer ?

**Comment by rscafi** [comment]
na verdade só usamos esse arquivo para os testes. dá pra fazer sem scripts nem nada, dentro do IoC. É bem tranquilo de fazer. O que rola é que não usamos o mongolid diretamente, utilizamos o [mongolid-laravel](https://github.com/leroy-merlin-br/mongolid-laravel/), que utiliza o container do laravel por baixo dos panos.

**Comment by lpj145** [comment]
cara vocês nem imaginam o quanto procurei vocês, estava desenvolvendo uma baseado nas features do firebase: 
https://github.com/orgs/FiremonPHP
mas, encontrei vocês agora, se me antender, vamos ficar de boa....

**Comment by rscafi** [comment]
Opa, qualquer dúvida/sugestão estamos aí!

**Comment by lpj145** [comment]
``Uncaught RuntimeException: Can't pop from an empty datastructure in C:\www\mongolidtest\vendor\leroy-merlin-br\mongolid\src\Mongolid\Connection\Pool.php:37``

Agora recebi isso, deve ser porque a estrutura de meu post não esta feita?

**Comment by rscafi** [comment]
Cara, acho que a gente tá devendo muito na documentação, sorry hahaha
Creio que nem precise mais do `bootstrap.php`. Pode tentar o código abaixo?

```php
<?php

require 'vendor/autoload.php';

use Mongolid\Manager;
use Mongolid\Connection\Connection;

$connection = new Connection('mongodb://localhost:27017');
$manager = new Manager();
$manager->addConnection($connection);

class Post extends Mongolid\ActiveRecord {
    protected $collection = 'posts';
}

$post = new \App\Posts();

$post::all();

**Comment by lpj145** [comment]
continuamos na mesma! hahaha

**Comment by lpj145** [comment]
mas eu to lendo o código, a documentação não ta muito longe não.

**Comment by lpj145** [comment]
![image](https://user-images.githubusercontent.com/11980109/30499039-58113086-9a2f-11e7-8d3a-9c2c89a3df23.png)

O erro esta batendo aqui.

![image](https://user-images.githubusercontent.com/11980109/30499058-6b55bf9a-9a2f-11e7-9de3-79a611c10b35.png)

**Comment by lpj145** [comment]
Resolvido, precisa usar o bootstrap ainda, porém existe um erro que o manager não possui construtor, logo como esta na documentação é um erro.

**Comment by lpj145** [comment]
Uma possibilidade, já que no formato atual funciona no laravel, mesmo sem construtor, o que acha se escerver um construtor, onde passando a conexão ele segue o fluxo do boostrap e vai ficar tudo bem ???

**Comment by lpj145** [comment]
#108

**Comment by lpj145** [comment]
#109

**Comment by lpj145** [comment]
#110
