### ISSUE TITLE
Not possible to project fields

### ISSUE THREAD

**Issue by NormySan** [leroy-merlin-br/mongolid#11]
Hi,

I'm doing a full text search with mongo and need to project the score field onto each document for sorting purposes but because of how mongolid handles selecting fields this is not possible.

How it works now is that mongolid takes each field passed and prepares them by flipping them and assigning a 1 to each field.

So doing something like this with mongolid wont work:

    $docs = Document::where(['$text' => ['$search' => 'some string']], ['score' => ['$meta' => 'textScore']]);

If i can come up with a good solution to this then i will try to do a pull request.

**Comment by rscafi** [comment]
Done in #57 for our new version 😉
