### ISSUE TITLE
Migrations and indexes support

### ISSUE THREAD

**Issue by GuilhermeGuitte** [leroy-merlin-br/mongolid#17]

**Comment by rscafi** [comment]
Should we migrate on mongolid or mongolid-laravel?
Related: leroy-merlin-br/mongolid-laravel#64

**Comment by gmsantos** [comment]
Indexing is a good case to be abstracted on Mongolid.

Leave this open, and tackle migrations on leroy-merlin-br/mongolid-laravel/#101

**Comment by ravanscafi** [comment]
Fixed in https://github.com/leroy-merlin-br/mongolid-laravel/pull/119
