### ISSUE TITLE
Unable to limit fields returned

### ISSUE THREAD

**Issue by ScottSpittle** [leroy-merlin-br/mongolid#34]
$this->account->where(['billing.status' => 'active'])->toArray(); Works Great.
$this->account->where(['billing.status' => 'active'], ['_id'])->toArray(); Not only returns invalid data (accounts with different status), but returns all the fields rather than just _id like I specified.

Am I doing something wrong here?

**Comment by ScottSpittle** [comment]
https://github.com/leroy-merlin-br/mongolid/pull/36

**Comment by rscafi** [comment]
Done in #57 for our new version 😉
