### ISSUE TITLE
`Serializer\Type\Converter` performance

### ISSUE THREAD

**Issue by Zizaco** [leroy-merlin-br/mongolid#77]
`toDomainTypes` and `toMongoTypes` have performance issues when looping through a cursor.

**Comment by rplansky** [comment]
The `Conventer` class was created in order to fix a known issue of MongoDB driver of version 1.1. So, with new MongoDB driver version, this class is unnecessary. I will remove it.

**Comment by rplansky** [comment]
Fixed in PR #91
