### ISSUE TITLE
Self relation/referencing feature

### ISSUE THREAD

**Issue by iNDicat0r** [leroy-merlin-br/mongolid#85]
Well I am well aware of relational data and that mongodb is a document db but there are some scenarios which mongolid wont work. 

Imagine a scenario to have a many to many relationship and an additional relationship which in my case is a self related model. Mongodb didnt insert the 'parent' model to the collection. Any ideas if there is a trick to implement self referencing?

**Comment by ravanscafi** [comment]
When dealing with self-references/parent-references, you should not use `embed`, but [`reference`](http://leroy-merlin-br.github.io/mongolid/relationships/#references-one) instead.
