### ISSUE TITLE
Problem with "Setup" mongolid in my project

### ISSUE THREAD

**Issue by tangalor** [leroy-merlin-br/mongolid#87]
Hi Zizaco,

I tried to use composer and I followed your guide, but following the "Setup" paragraph, I have a problem: I receive a fatal error because it can't find Manager.php.

So, I noticed that composer doesn't download me all the sources. For example, I noticed that into src/ there are only a few files, but for example there isn't Manager.php and so autoload can't find this file!

Can you help me to solve this problem?

Thanks, Tangalor

**Comment by rscafi** [comment]
Can you check which version is installed on your `composer.json` file?

**Comment by tangalor** [comment]
1.2.2

**Comment by rscafi** [comment]
Can you try `v2.0.0-beta8` or `v2.0.x-dev`?

**Comment by tangalor** [comment]
I'm sorry, it s 0.8.1 (and mongodb 1.0.0)

**Comment by tangalor** [comment]
ok, it's working with v2.0.0-beta8

Thank you!
