### ISSUE TITLE
Implement Countable interface for Cursors

### ISSUE THREAD

**Issue by rscafi** [leroy-merlin-br/mongolid#98]
Currently, we can't do a `count($cursor)` because our Cursors doesn't implement [Countable](http://php.net/manual/pt_BR/class.countable.php) interface. We can easily tackle this.

**Comment by vitorbari** [comment]
https://github.com/leroy-merlin-br/mongolid/pull/101

**Comment by gmsantos** [comment]
Moved #101 to Cursor interface
